config/routes.rb
Bibliotravel::Application.routes.draw do


  match 'discover' => "books#index", :via => :get
  match 'about' => 'welcome#about'
  match 'thanks' => 'welcome#thanks'
  match 'home' => 'welcome#home'


  resources :books
  resources :users
  
  post "sessions/create"
  get 'sessions/new'
  root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signin', to: 'sessions#new', as: 'signin'
  match 'signout', to: 'sessions#destroy', as: 'signout'


end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :provider, :oauth_expires, :oauth_secret, :oauth_token, :uid, :username
end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :blurb, :born, :died, :name, :city_id
  belongs_to :city
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  include InferredSlug::Slug

  attr_accessible :date, :title, :city_id, :author_id, :tags, :blurb, :isbn
  belongs_to :author
  belongs_to :city

  def slug
    tit = self.title.parameterize.strip
    tit.gsub! /['`]/, ''
    tit.gsub! /\s*[^A-Za-z0-9\.]\s*/, '-'
    tit.gsub! /-+/, '-'
    # tit.gsub! /\A[-\.]+|[-\.]+\z/, ''
    "#{id}-#{tit}"
  end

  def self.search(search)
    begin
      if search
        city_id = City.where(:name => search.titleize).first.id
        where('city_id = ?', city_id)
      else
        all
      end
    rescue
      nil
    end
  end

  

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country, :lat, :long, :name, :id
  has_many :authors
  has_many :books, :through => :authors


end

app/models/o_auth_user.rb
class OAuthUser

  require 'open-uri'

  attr_reader :provider, :user

  def initialize creds, user=nil
    @auth = creds
    @user = user
    @provider = @auth.provider
    @policy = "#{@provider}_policy".classify.constantize.new(@auth)
  end

  def login_or_create
    logged_in? ? create_new_account : (login || create_new_account)
  end

  def logged_in?
    @user.present?
  end

  private

  def login
    @account = Account.where(@auth.slice("provider", "uid")).first
    if @account.present?
      refresh_tokens
      @user = @account.user
      # @policy.refresh_callback(@account)
    else
      false
    end
  end

  def refresh_tokens
    @account.update_attributes(
      :oauth_token => @policy.oauth_token,
      :oauth_secret => @policy.oauth_secret,
      :oauth_expires => @policy.oauth_expires
      )
  end

  def create_new_account
    @user = User.where(email: @policy.email).first
    create_new_user if @user.nil?

    unless account_already_exists?
      @account = @user.accounts.create(
        :provider => @provider,
        :uid => @policy.uid,
        :oauth_token => @policy.oauth_token,
        :oauth_expires => @policy.oauth_expires,
        :oauth_secret => @policy.oauth_secret,
        :username => @policy.username
        )
      @user.update_attribute(picture_url: image)
      @policy.create_callback(@account)
    end
  end

  def account_already_exists?
    @user.accounts.exists?(provider: @provider, uid: @policy.uid)
  end

  def create_new_user
    @user = User.create(
      :first_name => @policy.first_name,
      :last_name => @policy.last_name,
      :email => @policy.email,
      :picture_url => image
      )
  end

  def image
    # image = open(URI.parse(@policy.image_url), :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE)
    # def image.original_filename; base_uri.path.split('/').last; end
    # image
    @policy.image_url
  end

  
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  belongs_to :book
  attr_accessible :ranking, :source, :book_id
end

app/models/regular_user.rb
class RegularUser < User

  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  validates :email, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  include InferredSlug::Slug

  has_many :accounts, :dependent => :destroy
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :picture_url

  def slug
    "#{id}-#{first_name}-#{last_name}"
  end

  def facebook
    o_token = self.accounts.where(provider: 'facebook').first.oauth_token
    @facebook ||= Koala::Facebook::API.new(o_token)
  end

  def has_facebook?
    accounts.where(provider: 'facebook').any?
  end

  def has_twitter?
    accounts.where(provider: 'twitter').any?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    # to filter using tags:
    # @books = Book.where('classics' = ANY (tags))
    @city = params[:search]
    @books = Book.search(@city)
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if request.env["omniauth.auth"].present?
      oauth = OAuthUser.new(request.env["omniauth.auth"], current_user)
      oauth.login_or_create
      session[:user_id] = oauth.user.id
      redirect_to current_user

    else
      user = RegularUser.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id]    = user.id
        redirect_to current_user

      else
        flash.now[:error] = "Invalid login credentials."
        render action: 'new'
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user, only: [:edit, :update]

  def new
    @user = RegularUser.new
  end

  def edit
    @user = RegularUser.find(current_user.id)
  end

  def update
    @user = RegularUser.find(current_user.id)
    if @user.update_attributes(params[:regular_user])
      redirect_to root_path
    else
      render action: 'edit'
    end
  end

  def create
    @user = RegularUser.new(params[:regular_user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'User successfully created.'
      redirect_to current_user
    else
      flash.now[:alert] = 'User creation failed, try again'
      render action: 'new'
    end
  end

  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    city = request.location.city
    @city = City.where(:name => city.titleize).first
    if @city.nil?
      @city = City.first
    end
  end

  def about
  end

  def thanks
  end

  def home
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

  require 'amazon/ecs'

  Amazon::Ecs.options = {
    :associate_tag => 'bookcities-20',
    :AWS_access_key_id => ENV['AMAZON_KEY'],
    :AWS_secret_key => ENV['AMAZON_SECRET']
  }



  def book_cover_helper item
    res = Amazon::Ecs.item_search(item.isbn, { :response_group => 'Images'} )
    img_hash = res.items.first.get_hash('LargeImage')
    image_tag(img_hash['URL'], :size => '193x300')
    # img = "http://covers.librarything.com/devkey/#{ENV["LIB_THING_KEY"]}/large/isbn/#{item.isbn}"
    # img.size == 0 ? image_tag('default_cover.png') : image_tag(img)
  end

  def book_tags_helper item
    tags_set = Set.new
    tags_set.merge(item.tags)
    res = ''
    tags_set.each do |t|
      res << content_tag(:li, :class => 'btn filter', :data => { :filter => t }) do
        t.titleize
      end
    end
    res
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_celeb.html.erb
<div id="celeb">

  <h2>Nick Hornby's top 3 London novels.</h2
  <%= image_tag('hornby.jpg') %>

   <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Author</th>
        <th>Title</th>
        <th>Comments</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Charles Dickens</td>
        <td>David Copperfield</td>
        <td>I love the minor characters.</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Charles Dickens</td>
        <td>Great Expectations</td>
        <td>Seemed boring at first but it's a real pleasure when you get into it.</td>
      </tr>
      <tr>
        <td>3</td>
        <td>Zadie Smith</td>
        <td>White Teeth</td>
        <td>Very much hilarious.</td>
      </tr>
    </tbody>
  </table>
</div>

<div id="celeb">

<h2>Michael Bloomberg's top 3 New York novels.</h2
  <%= image_tag('bloomberg.jpg') %>

   <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Author</th>
        <th>Title</th>
        <th>Comments</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Nicolo Machiavelli</td>
        <td>The Prince</td>
        <td>I can relate to this book. Inspiring, totally takes place here.</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Jonathan Lethem</td>
        <td>Motherless Brooklyn</td>
        <td>A new tale of old New York. A must read for all these noisome hipsters.</td>
      </tr>
      <tr>
        <td>3</td>
        <td>Thom Wolfe</td>
        <td>The Bonfire of the Vanities</td>
        <td>Ah, remeinds me of the good old 80s at Solomon Bros... But I didn't kill anyone.</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/books/_form.html.erb
<h1>Add a new book</h1>

<%= simple_form_for @book do |f| %>
  <%= f.input :author %>
  <%= f.input :title %>
  <%= f.input :city %>
  <%= f.input :date %>
  <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<% unless @books.nil? %>
  <h1>Here are your books for <strong><%= @city.titleize %></strong>!</h1>
<% else %>
  <h1>We could not find any titles for <%= @city.titleize %>.</h1>
<% end %>
<ul>
  <li class="btn filter" data-filter='all'>View All</li>
  <% unless @books.nil? %>
    <% @books.each do |b| %>
      <% unless b.tags.nil? %>
        <% b.tags.each do |t| %>
          <li class="btn filter" data-filter="<%= t %>"><%= t.titleize %></li> 
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</ul>

<ul id="Grid">
  <% unless @books.nil? %>
    <% @books.each do |b| %>
      <div class="book mix <%= b.tags.join(' ') unless b.tags.nil? %>">
          <%= book_cover_helper(b) %>
          <div class="blurb">
            <p><%= link_to b.title, b %></p>
            <p><%= b.author.name %></p>
            <p><%= b.blurb %></p>
            <%= link_to 'Buy text!', '#', class:  'buy btn'%>
          </div>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/books/modal_show.html.erb
<h2>Details for <strong><%= @book.title %></strong></h2>:
<table>
  <tr>
    <p><%= @book.author.name %><p>
    <p><%= @book.blurb %><p>
    <p>Tagged under: <%= @book.tags.join(', ') %></p>

    <div class="exerpt">
      <%= link_to 'Read an excerpt', '#', class: 'btn', role: 'button', data: { :show => true, :target => "##{@book.isbn}Modal"}%>
      <%= link_to 'Buy text!', '#', class:  'buy btn'%>
    </div>
  </tr>
</table>
<h4><%= @book.title %> has been recommended by these local writers and authorities:</h4>

<!-- mock out the display here - sort of like Discourse app maybe... -->
<!-- MODAL experiment -->
<div id="<%= @book.isbn %>Modal" class="modal hide fade" >
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>Your excerpt, fine sir:</h3>
  </div>
  <div class="modal-body">
    <p>She would not say of any one in the world now that they were this or were that. She felt very young; at the same time unspeakably aged. She sliced like a knife through everything; at the same time was outside, looking on.She had a perpetual sense, as she watched the taxi cabs, of being out, out, far out to sea and alone; she always had the feeling that it was very, very dangerous to live even one day. Not that she thought herself clever, or much out of the ordinary. How she had got through life on the few twigs of knowledge Fräulein Daniels gave them she could not think. She knew nothing; no language, no history; she scarcely read a book now, except memoirs in bed; and yet to her it was absolutely absorbing; all this; the cabs passing; and she would not say of Peter, she would not say of herself, I am this, I am that.

    Her only gift was knowing people almost by instinct, she thought, walking on. If you put her in a room with some one, up went her back like a cat's; or she purred. Devonshire House, Bath House, the house with the china cockatoo, she had seen them all lit up once; and remembered Sylvia, Fred, Sally Seton — such hosts of people; and dancing all night; and the waggons plodding past to market; and driving home across the Park. She remembered once throwing a shilling into the Serpentine. But every one remembered; what she loved was this, here, now, in front of her; the fat lady in the cab. Did it matter then, she asked herself, walking towards Bond Street, did it matter that she must inevitably cease completely; all this must go on without her; did she resent it; or did it not become consoling to believe that death ended absolutely? but that somehow in the streets of London, on the ebb and flow of things, here, there, she survived, Peter survived, lived in each other, she being part, she was positive, of the trees at home; of the house there, ugly, rambling all to bits and pieces as it was; part of people she had never met; being laid out like a mist between the people she knew best, who lifted her on their branches as she had seen the trees lift the mist, but it spread ever so far, her life, herself. But what was she dreaming as she looked into Hatchards' shop window? What was she trying to recover? What image of white dawn in the country, as she read in the book spread open:

    Fear no more the heat o' the sun

    Nor the furious winter's rages.</p>
  </div>
  div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/books/old_index.html.erb
<h1>Here are your books for <strong><%= @city.titleize %></strong>!</h1>
<table class="table-striped">
  <thead>
    <tr>
      <td>Title</td>
      <td>Author</td>
      <td>Summary</td>
      <td>Purchase</td>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |b| %>
      <tr>
        <td><%= image_tag "http://covers.librarything.com/devkey/#{ENV["LIB_THING_KEY"]}/large/isbn/#{b.isbn}" %></td>
        <td><strong><%= link_to b.title, books_show_path(b) %></strong></td>
        <td><%= b.author.name %></td>
        <td><%= b.blurb %></td>
        <td><%= link_to 'Buy from Powells', '#', class: 'btn btn-custom-lighten' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
<div id="user_nav">
  <% if current_user.present? %>
    Signed in as <strong><%= current_user.name %></strong>
    <%= link_to 'Sign out', signout_path %>
  <% end %>
</div>

app/views/layouts/_search.html.erb
<% form_tag books_show_path, :method => :get do %>
<p>
  <%= text_field_tag :search, params[:search]  %>
  <%= submit_tag 'Search', :name => nil %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>BookCities</title>
    <meta name="description" content="Find the perfect book for your trip.">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->


<div class="container-fluid">
      <header class="row-fluid">
          <div class="span4">
            <%= link_to (image_tag "logo-wide.png"),  root_path, :id => "logo", :alt => "BookCities" %>
          </div>
          <div class="sign_out">
            <% if current_user.present? %>
              <%= link_to 'Sign out', signout_path %>
            <% end %>
          </div>

      </header>


<%= yield %>
          <footer>
              <div class="masthead" >
                  <ul class="nav nav-pills pull-left">
                  <div class="contact">
                      <%= link_to 'About', about_path %>
                      <%= mail_to 'charlie.gaines@gmail.com', 'Contact Us', :encode => 'hex' %>
                      <%= link_to 'Thanks', thanks_path %>
                  </div>
                  </ul>
                  <ul class="nav nav-pills pull-right">
                    <li>&copy; 2013 Bookcity</li>
                  </ul>
              </div>
          </footer>
  </div>
</body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41462905-1', 'bookciti.es');
  ga('send', 'pageview');

</script>

app/views/users/_form.html.erb
<div class="sign_up">
  <% url = (@user.new_record? ? users_path : user_path(@user)) %>

  <%= simple_form_for @user, :url => url do |f| %>
    <%= f.error_notification %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.button :submit, 'Create Account' %>
  <% end %>

  <p>Already have an account?  <%= link_to 'Sign in', signin_path %></p>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to Book Cities!  Now you can contribute to the revolution in book discover.</h1>
<%= link_to 'Add a new book!', '#' %>

app/views/welcome/_oldindex.html.erb
<div class="span10" id="landing" class="clearfix">
<div class="span9"> <!-- Hero Unit -->



          <% unless current_user.present? %>
            <div class="hero-unit">
                        <%= image_tag "logo.png", :id => "logo"%>
              <h1>Welcome to Book City!</h1>
                <p> You can search for books that take place in <strong>
                  <%= @city.name %>
                </strong> or find a good book that takes place in another city.</p>
                <%= link_to 'Sign in with Facebook to get started', '/auth/facebook', id: 'sign_in' %>
            </div> <!-- Hero Unit -->
          <% end %>

            <% if current_user.present? %>
             <p> Welcome back!</p>
             <section class="books">
               <p>Here are some books that take place in <strong><%= @city.name %></strong>:</p>
               <table class='table-striped'>
                <thead>
                  <th>Title</th>
                  <th>Author</th>
                </thead>
                <tbody>
                <% @books.each do |b| %>
                  <tr>
                     <td><%= b.title %></td>
                     <td><%= b.author.name %></td>
                  </tr>
                 <% end %>
                </table>
              </section>
              <section class="authors">
                <p>Here are some authors associated with <strong><%= @city.name %></strong>:</p>
                  <table class='table-striped'>
                  <thead>
                    <th>Name</th>
                    <th>Bio</th>
                  </thead>
                  <tbody>
                  <% @authors.each do |a| %>
                    <tr>
                       <td><%= a.name %></td>
                      <td><%= image_tag 'melville.jpg' %></td>
                       <td><%= a.blurb %></td>
                    </tr>
                  <% end %>
              </section>
              <section class="events">
                <p>And here are some famous literary events from <strong><%= @city.name %></strong></p>
              </section>
           <% end %>

app/views/welcome/about.html.erb
<p class="lead">Let's say that you are about to visit Paris for the first time. You booked your flight and hotel, found a map, and planned which museums to visit. But what should you read on the plane and on the metro?</p>

<p>What better time to read <em>A Moveable Feast</em>? This is your chance to experience the book and the city on higher level. You can read about Ernest Hemingway's exploits while you stroll the same neighborhoods as he did in the 1920s.</p>

<p><strong>BookCities</strong> suggests novels that are set in your travel destination - or helps you find books for the city you live in. If you <a href="#">sign in with Facebook</a>, you can receive book recommendations based on your tastes and those of your friends.</p>

<p>Coming soon:  book recommendations from local authors and residents, local literary lore and anecdotes, and maps to guide you through the streets, cafes, libraries that great authors have called home.</p>

app/views/welcome/home.html.erb
<div class="media profile">
  <a class="pull-left" href="#">
    <%= image_tag "c_gaines.png", size: '128x128', class: 'media-object' %>
  </a>
  <div class="media-body">
    <h2 class="media-heading">Welcome Charlie!</h2>
    <h4>Your favorites:</h4>
      <ul>
        <li>The Idiot</li>
        <li>Collected Short Stories of Paul Bowles</li>
        <li>Ulysses</li>
      </ul>
    <h4>Recommended by you:</h4>
      <div class="rec">
        <h5>Jorge Luis Borges - Poems of the Night (Dual Language Edition)</h5>
        <p><em>"Borges is most revered for his magnificent works of fiction, yet he thought of himself primarily as a poet. Poems of the Night is a moving collection of the great literary visionary's poetic meditations on nighttime, darkness, and the crepuscular world of visions and dreams."</em></p>
      </div>
    <div class="rec">
      <h5>Michael Lavocah - Tango Stories</h5>
      <p><em>"A must for those going to Buenos Aires who want to really understand Argentine culture.  Lavocah introduces the picaresque and dramatic characters who shaped tango history, telling their stories in a series of lively vignettes. If you don't dance tango now, you'll want to after reading this book."</em></p>
    </div>
  </div>
</div>



<section class="recs">
<h3>Your personalized recommendations:</h3> 
  <div class="media">
    <a class="pull-left" href="#">
      <%= image_tag "gaucho_martin.jpg", size: '128x128', class: 'media-object' %>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><em>El Gaucho Martin</em>, Jose Fernandez</h4>
      <p>Argentina's greatest poet of the 1970s tells the tales of gauchos and the pampas with typical Argentine passion and panache.</p>
    </div>
  </div>
  <div class="media">
    <a class="pull-left" href="#">
      <%= image_tag "donkey.gif", size: '128x128', class: 'media-object' %>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><em>Arabian Sands</em>, Wilfred Thesiger</h4>
      <p>One of the world's last great explorers, Thesiger tells the remarkable story of his pioneering travels in the <em>Rub al'Khalil</em>, the Empty Quarter of the Arabian desert.</p>
    </div>
  </div>

  <div class="media">
    <a class="pull-left" href="#">
      <%= image_tag "sarah_and_the_crab.jpg", size: '128x128', class: 'media-object' %>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><em>Sarah and the Crab</em>, Sarah Palin</h4>
      <p>In this riveting coming-of-age story, Sarah Palin recounts her early childhood encounter with an enormous Alaskan king crab.</p>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
        <div class="hero-unit">
            <h1>Discover the right book for your trip.</h1>
            <p class="lead">A good novel heightens the experience of a new city. BookCities can help you find the best read based on your destination. Just pick a place and go!</p>
            <div class="row3">
                <%= form_tag discover_path, :method => 'get' do %>
                    <div class="field search">
                        <%= text_field_tag :search, params[:search], :placeholder => 'Take me to...' %>
                        <%= submit_tag 'Go!', :name => nil, :class => 'btn btn-custom-lighten'%>
                    </div>
                <% end %>
<!--                 <form class="form-search" id="search">
                    <input type="text" class="input-large search-query" placeholder="Take me to...">
                    <button type="submit" class="btn">Go!</button>
                </form>
 -->            </div>
        </div>
        <div class="row-fluid marketing">
          <div class="span6" class="frontsections">
             <h4><button class="btn btn-custom-lighten btn-block">Suggestions for <%= @city.name %></button></h4>
             <p>Find novels set in your current city here.</p>
        </div>
            <div class="span6" class="frontsections">
                <h4><button class="btn btn-custom-lighten btn-block">Personalized Recommendations</button></h4>
                <% unless current_user %>
                    <p><%= link_to 'Sign in with Facebook', "/auth/facebook" %> to get book suggestions based on what your friends like.</p>
                <% end %>
            </div>
        </div>
        <div class="row-fluid marketing" class="frontsections">
            <div class="span6">
             <h4><button class="btn btn-custom-lighten btn-block">Share</strong></button></h4>
             <% unless current_user %>
                <p>No books for your city?  <%= link_to 'Sign up', new_user_path  %> and add them.</p>
                <p>Already signed up?  <%= link_to 'Sign in', signin_path %></p>
             <% end %>
        </div>
            <div class="span6" class="frontsections">
              <h4><button class="btn btn-custom-lighten btn-block">Literary Tourism</button></h4>
              <p>Discover local authors' birthplaces, haunts and graves.</p>
            </div>
        </div>


        </div> <!-- /container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <!-- <script src="js/vendor/jquery-ui-1.10.3.custom.min.js"></script> -->

        <!-- <script src="js/vendor/bootstrap.min.js"></script> -->

        <!-- <script src="js/main.js"></script> -->

        <script>
        //     var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        //     (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        //     g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        //     s.parentNode.insertBefore(g,s)}(document,'script'));
        // </script>
    </body>
</html>